name: Test Task
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMIT_NAME: ${{ github.event.head_commit.message }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      GO111MODULE: auto
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      # - name: Install dependencies
      #   run: go get .
      # - name: Build
      #   run: go build -v ./...
      - name: Test task
        run: |
          echo ${{ env.BRANCH_NAME }}
          cd ${{ env.BRANCH_NAME }}
          go test -v
